### ISSUE TITLE
JSON -  Magie? ✨ 

### ISSUE THREAD

**Issue by robert-hoekstra** [Wiebsonice/functional-programming#2]
In jouw code en documentatie kom ik tegen dat je de JSON file importeert ergens vandaan. Ik ben nog niet zo geavanceerd met programmeren. Maar ik kan niet achterhalen wat nou precies de bron is van jouw JSON file. Haal je ergens lokaal vandaan?

**Comment by Wiebsonice** [comment]
Yes, die is lokaal, en word ingeladen met de import functie. (en is ge gitignored).

Solved in commit `e3e31fa`
