### ISSUE TITLE
Feedback documentatie

### ISSUE THREAD

**Issue by roberrrt-s** [Wiebsonice/functional-programming#4]
Mooie documentatie, hele goede guide door je proces + veel details over wat je doet, en waarom je dingen doet. Kijk nog even de twee issues na die hier openstaan, verder kan ik deze URL niet bezoeken:
https://github.com/Wiebsonice/functional-programming/wiki/Functional-VS-Object-oriented
Veel succes morgen

**Comment by Wiebsonice** [comment]
Thanks!, Aangepast.
